### ISSUE TITLE
Archlinux freezes after kexec

### ISSUE THREAD

**Issue by lynxred** [osresearch/heads#1117] opened 2022-02-19 01:05 UTC
How to disable adding extra kernel options? intel_iommu=on intel_iommu=igfx_off were added to the other from the file grub.cfg. As a result, the system does not load on and freeze on the message Starting new kernel. My system archlinux with luks conteiner. i trying delete quiet option but without a result

**Comment by tlaurion** [comment] 2022-02-20 14:01
@lynxred Those options come from the board configuration in ADD_KERNEL boot option. Those are the parameters passed to the final OS cmd line.

What board are we talking about?

**Comment by lynxred** [comment] 2022-02-20 14:06
Hi @tlaurion! My board is x230.  I am facing the same problem both when booting the OS from the ssd and when installing the OS cube. the laptop hangs on the message Starting new kernel.

**Comment by lynxred** [comment] 2022-02-20 14:51
I I added the parameters to the config.user file and yes, when they are loaded, they are no longer there. But the laptop freezes at the same step

**Comment by tlaurion** [comment] 2022-02-20 14:58
I'm confused about your report on Qubes installer not booting, since I tested a couple of days ago on i5 with latest commit containing microcode updates for both 4.1 and 4.0.4 installer from iso with detached signatures.

Can you flash CircleCI build to confirm its not the locally built ROM that is at fault? 

Are you booting from ISO or dd'ed image?

**Comment by lynxred** [comment] 2022-02-20 15:00
I try in dd.

**Comment by tlaurion** [comment] 2022-02-20 15:00
> I I added the parameters to the config.user file and yes, when they are loaded, they are no longer there. But the laptop freezes at the same step

So we can agree that those parameters are not at fault

**Comment by lynxred** [comment] 2022-02-20 15:01
> So we can agree that those parameters are not at fault

and now I don't understand what the problem is

**Comment by lynxred** [comment] 2022-02-20 15:05
> > I I added the parameters to the config.user file and yes, when they are loaded, they are no longer there. But the laptop freezes at the same step
> 
> So we can agree that those parameters are not at fault

Now I am compiling your forked repo. I'll let you know the results later

**Comment by tlaurion** [comment] 2022-02-20 15:06
The reason I prefer booting with iso and detached signature is that it confirms there is no integrity problem nor flash memory issue from booted medium.

For Qubes, having the ISO and .asc accompanying file, and booting from USB will validate the integrity and authenticity of the image prior of booting.

For Arch, I would recommend verifying the iso saved on flash media as well from external OS. 

I could try to test booting from dd'ed verified qubesos image in the next days, while present hypothesis is probably integrity problem?

On arch already installed on disk, I would love to see the frozen kexec command at the bottom since I'm not a arch user. But Qubes works. I remember having seen other arch issues in the past, have you reviewed them?

**Comment by lynxred** [comment] 2022-02-20 15:09
Yes, I've looked at other threads. I can record a video booting from an ssd disk installed archlinux and booting a cube from a flash drive and iso

**Comment by tlaurion** [comment] 2022-02-20 15:10
> Now I am compiling your forked repo. I'll let you know the results later

Please follow those instructions to test builds from CircleCI.
This is what I tested, so we have the same ROM tested.

https://github.com/osresearch/heads-wiki/issues/88

**Comment by tlaurion** [comment] 2022-02-20 15:12
> Now I am compiling your forked repo. I'll let you know the results later

My master is really old, I create branch there and push them as pull requests only. Building that will not represent anything useful!

**Comment by lynxred** [comment] 2022-02-20 15:14
Cool! Thanks. And I compile the firmware in a local docker container

**Comment by lynxred** [comment] 2022-02-20 15:53
I try this flash:
**heads-x230-v0.2.0-1153-gc1409a8.rom**: I didn't see any changes in the loading iso. The laptop still hangs on the message and then turns off after 5 minutes.
heads-x230-hotp-maximized-v0.2.0-1153-gc1409a8.rom: Ooooops Black screen after flashing.....

**Comment by tlaurion** [comment] 2022-02-20 16:06
... Maximized builds need to be externally flashed externally from the two top and bottom flash images, or internally from the 12 mb image.

So to get things straight: x230 i5 or i7.
Booting from qubes 4.0.4 being first verified and then dd'ed on USB thumb drive.

Will retest x230 image produced from CI on dd'ed USB drive when I have a chance.

**Comment by tlaurion** [comment] 2022-02-20 16:08
HOTP are different the non HOTP in the sense they require HOTP compliant USB security dongles (Librem Key/ Nitrokey pro/ Nitrokey Storage)

**Comment by lynxred** [comment] 2022-02-20 16:10
It's normal that hotp has a black screen after loading.

**Comment by lynxred** [comment] 2022-02-20 16:18
My board x230 i7. heads-x230-v0.2.0-1153-gc1409a8.rom i try loading ISO file (no dd). I have backup files of the lower and upper chip. Can you tell me how to restore them using raspberry pi?) Can we continue the conversation in my telegram?))

**Comment by tlaurion** [comment] 2022-02-20 16:20
No, it's not.

I would suggest flashing x230-maximized build from CircleCI on top and bottom SPI. Those are the most tested ROMs.

x230 rom or x230-hotp-verification ROMs are to be flashed internally from x230-flash.

Your laptop shutdowning after 5 minutes is also not normal. Last time From memory, ME being invalid would shutdown the main CPU after 30 minutes. 

From past observed failures of kexec not being able to boot OS kernel and initrd, it normally just hangs there forever.

**Comment by tlaurion** [comment] 2022-02-20 16:21
@lynxred 

>My board x230 i7. heads-x230-v0.2.0-1153-gc1409a8.rom i try loading ISO file (no dd). I have backup files of the lower and upper chip. Can you tell me how to restore them using raspberry pi?) Can we continue the conversation in my telegram?))

Restoring it the other way around.
Flash original 4mb on top SPI, 8mb on bottom SPI.

**Comment by lynxred** [comment] 2022-02-20 16:25
> I would suggest flashing x230-maximized build from CircleCI on top and bottom SPI. Those are the most tested ROMs.

Good! I try this.
Tell me. Is it possible to flash with raspberry pi? Are there detailed instructions on how to do this?

**Comment by tlaurion** [comment] 2022-02-20 16:32
How did you flashed Heads ?

**Comment by lynxred** [comment] 2022-02-20 16:33
I updated from the skulls firmware

**Comment by lynxred** [comment] 2022-02-20 16:37
I dont see x230-maximized build o_O.....
https://app.circleci.com/pipelines/github/osresearch/heads/379/workflows/ad993019-d3bb-4bea-abe7-041e43cd273d

**Comment by tlaurion** [comment] 2022-02-20 16:40
> I dont see x230-maximized build o_O.....
> https://app.circleci.com/pipelines/github/osresearch/heads/379/workflows/ad993019-d3bb-4bea-abe7-041e43cd273d

Damnit. Seems like I forgot to add it back on CI....

**Comment by tlaurion** [comment] 2022-02-20 16:40
> Tell me. Is it possible to flash with raspberry pi? Are there detailed instructions on how to do this?

Instructions can easily found in the internet

One examokenis from the Skulls project

https://github.com/merge/skulls/blob/master/x230/README.md

**Comment by lynxred** [comment] 2022-02-20 16:41
okay okay) I think it's a good idea to add it to the wiki?)

**Comment by tlaurion** [comment] 2022-02-20 16:42
> I updated from the skulls firmware. https://github.com/merge/skulls/tree/master/x230#moving-to-heads

Ha. Then having flashed blindly maximized build has caused a brick :/

**Comment by lynxred** [comment] 2022-02-20 16:47
> 

>_> I wait x230-maximized build and  I'm trying to restore this brick. the laptop was for $50 and I gained experience in many areas)

**Comment by lynxred** [comment] 2022-02-20 16:48
>_> I wait x230-maximized build and  I'm trying to restore this brick. the laptop was for $50 and I gained experience in many areas)

**Comment by lynxred** [comment] 2022-02-20 16:48
-_- I wait x230-maximized build and  I'm trying to restore this brick. the laptop was for $50 and I gained experience in many areas)

**Comment by tlaurion** [comment] 2022-02-20 17:42
Build happening under #1119

**Comment by tlaurion** [comment] 2022-02-20 19:07
Artifacts for x240-maximized are here: https://app.circleci.com/pipelines/github/tlaurion/heads/978/workflows/ab9dff67-6362-4cca-b46e-b31d25b8508e/jobs/4515/artifacts

Flash top and bottom

**Comment by lynxred** [comment] 2022-02-21 11:46
good news! i flashed the bios chips using my raspberry.  so. i am testing iso boot and boot my arch
iso boot: working(freeze in boot graphical mose).
usb dd image: working(freeze in boot graphical mode)
my archlinux start: nope.....
Can you help setting boot parameter for my arch?
my arch boot parameter next:
![image](https://user-images.githubusercontent.com/40891438/154949300-afbc8763-0c1f-416c-a415-7cb39286d280.jpeg)

**Comment by tlaurion** [comment] 2022-02-21 15:29
Ok.

Let's do this correctly step by step:

Flashed externally (commit 7601400 as in firmware name):
- https://4515-103208611-gh.circle-artifacts.com/0/build/x230-maximized/heads-x230-maximized-v5.0.1-102-g7601400-bottom.rom 
- https://4515-103208611-gh.circle-artifacts.com/0/build/x230-maximized/heads-x230-maximized-v5.0.1-102-g7601400-top.rom

You are now in a clean state (without public key injected, not TPM sealed TOTP/HOTP. Here no HOTP support in).

What interests me here is what is happening and why you can't boot Q4.1 or Q4.0.4, which are the most tested. What is different on your side? Please share screenshots in portrait mode. 
1. Power on laptop.
![signal-2022-02-21-101949_006](https://user-images.githubusercontent.com/827570/154983776-6fb80d52-c853-4e34-ac0e-ce254d613958.jpeg)
1. Validate system info, send capture.
![signal-2022-02-21-102428](https://user-images.githubusercontent.com/827570/154984347-6365797c-fb6a-429d-a64a-2777faaaf8c6.jpeg)
![signal-2022-02-21-102355](https://user-images.githubusercontent.com/827570/154984536-5155cf62-64b9-49de-beb1-269b26092e3b.jpeg)
1. Boot from Qubes 4.0.4 ISO (with detached signature in the same directory)
![signal-2022-02-21-101949_005](https://user-images.githubusercontent.com/827570/154983799-bd09e766-7002-4ac2-8771-d0b54c8a99d6.jpeg)
![signal-2022-02-21-101949_004](https://user-images.githubusercontent.com/827570/154983808-2bac6d1f-75f1-4a5f-840c-cf51435b0182.jpeg)
![signal-2022-02-21-101949_003](https://user-images.githubusercontent.com/827570/154983821-0a990a84-2374-4c15-bd60-42cd447b4690.jpeg)
![signal-2022-02-21-101949_002](https://user-images.githubusercontent.com/827570/154983848-f4c34396-42e3-4806-85f1-cde81f63841a.jpeg)
![signal-2022-02-21-101949_001](https://user-images.githubusercontent.com/827570/154983873-ac65fbc4-d7b0-435c-a3c0-d6e3319fe4b2.jpeg)
1. Enjoy the installer
![signal-2022-02-21-102114](https://user-images.githubusercontent.com/827570/154983895-88ed5760-8f62-49ae-9b9e-36b0db1a5494.jpeg)

**Comment by lynxred** [comment] 2022-02-21 16:46
I flashed 760140
![image](https://user-images.githubusercontent.com/40891438/154996267-a3efe1de-cb21-4c3b-90d9-d686274373d1.jpeg)
and working in type 7 and freeze type 9
![image](https://user-images.githubusercontent.com/40891438/154996399-44fc1e42-ac4d-43b1-a300-c3a0e3cbc17f.jpeg)

It looks like I need to test the work on other distributions (non-qube).  but I think that this topic can be closed since I managed to install the qube os.

**Comment by tlaurion** [comment] 2022-02-21 17:43
Qubes OS doesn't even install in basic graphic mode. So totally irrelevant. Not sure why they even propose the option.

**Comment by tlaurion** [comment] 2022-02-21 17:45
@lynxred please close after having given short version of what solved the issue for you, or what user error was linked to opening the issue at first place.

Arch is still unfixed AFAIK.

**Comment by lynxred** [comment] 2022-02-22 19:21
tell me how to configure boot os with these grub parameters. qube os working but I need archlinux with encrypted root. in attachment screenshot boot parameter ![image](https://user-images.githubusercontent.com/40891438/155203545-4035cb2a-d5d1-4c0f-9c6f-9c3c88e16c8d.jpeg)

**Comment by tlaurion** [comment] 2022-02-22 20:03
@lynxred I have pushed a PR yesterday that fixes the booting from Archlinux under #1120 which is currently under review.
I am not using Archlinux unfortunately, but have changed the name of your issue to attract other users having the same needs.

At first view of last screenshot, it seems that only intel-ucode is passed as initrd, but I may be talking over my head completely here. The issue #702 covered a bit an issue with Archlinux. You might want to tag other people having reported issues in the past to get some help?

**Comment by tlaurion** [comment] 2022-02-22 20:06
As far as I know reading #702, this issue is a duplicate of #702.

**Closed** 2022-02-22 20:06 UTC
