### ISSUE TITLE
Please secure your website asap

### ISSUE THREAD

**Issue by baimafeima** [osresearch/heads#468] opened 2018-10-17 17:18 UTC
Please secure your website. It is currently not TLS-secured and please test web servers with the usual tools. Thank you.

**Comment by merge** [comment] 2018-10-18 11:55
The website is generated from the heads-wiki project so I guess this is a duplicate of https://github.com/osresearch/heads-wiki/issues/14 and can be closed

**Comment by osresearch** [comment] 2018-11-07 21:50
@merge is right that this is a dupe. There seems to be something wrong with github's letsencrypt integration for the site -- it says "try again in 24 hours" and has for the past few months.

**Closed by osresearch** 2018-11-07 21:50 UTC
